name: Install Linux packages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Before
      run: |
        which ack || echo ack is missing

    - name: Install package
      run: |
        sudo apt-get -y install ack

    - name: Try ack
      run: |
        which ack || echo ack is missing
        which ack
        ack package

