name: Install Linux packages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Before
      run: |
        which black || echo black is missing
        black

#    - name: Install package
#      run: |
#        sudo apt-get -y install ack
#
#    - name: Try ack
#      run: |
#        set -x
#        which ack || echo ack is missing
#        which ack
#        ack --help
#        tree
#        ls -al
#        df -h
#        cat README.md
#        echo hello
#
#    - name: Try grep
#      run: grep Linux *
#    - name: Try ack
#      run: ack Linux

