name: Install Linux packages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Before
      run: |
        which black || echo black is missing

    - name: Install package
      run: |
        sudo apt-get -y install black

    - name: Try black
      run: black .
      # Use `black --check .` to verify the formatting and make the CI fail if it needs updating.needs updating.

    - name: diff
      run: git diff

